server:
  port: 6868 #服务端口


spring:
  application:
    name: yit-eureka #指定服务名


eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中，本身就是所有无需注册
    fetchRegistry: false #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://yitdev:yit123@127.0.0.1:6868/eureka/
  #instance:
    #prefer-ip-address: true
      #ip-address: 127.0.0.1

security:
  basic:
    enabled: true
  user:
    name: yitdev  # 用户名
    password: yit123  # 用户密码

